baseURL: https://ahzed11.github.io/
languageCode: en-us
title: "Alexandre Zenon"
description: "My blog"
author: "Alexandre Zenon"
theme: "PaperMod"

params:
  outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary

  defaultTheme: auto

  homeInfoParams:
    Title: "Welcome to my blog"
    Content: Hi, I am a computer science student at UCLouvain, Belgium.

  socialIcons:
    - name: github
      url: "https://github.com/Ahzed11"
    - name: linkedin
      url: "https://www.linkedin.com/in/alexandre-zenon/"
    - name: itchio
      url: "https://ahzed.itch.io/"
    - name: kofi
      url: https://ko-fi.com/ahzed11
    - name: rss
      url: "https://ahzed11.github.io/index.xml"

  ShowReadingTime: true

  ShowToc: true
  TocOpen: false

  env: production

  ShowCodeCopyButtons: true

  ShowPostNavLinks: true
